# Generated by Django 3.0 on 2021-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_newdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='mobile',
            field=models.IntegerField(default=9346222580),
        ),
    ]
